# Generated by Django 2.2.13 on 2020-09-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='receive',
            field=models.BooleanField(default=False),
        ),
    ]
