# Generated by Django 2.2.13 on 2020-09-09 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sqp', '0001_squashed_0004_auto_20200909_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userproducts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='verify',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activate', to=settings.AUTH_USER_MODEL),
        ),
    ]
