# Generated by Django 2.2.13 on 2020-09-09 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sqp', '0002_auto_20200909_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verify',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verify', to=settings.AUTH_USER_MODEL),
        ),
    ]
