# Generated by Django 2.2.13 on 2020-09-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqp', '0002_pay_receive'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
