services:
  sqpb:
    build:
      context: back
      target: base
    command: gunicorn back.asgi:application -k uvicorn.workers.UvicornWorker --reload
    volumes:
      - ./back:/usr/src/app
    networks:
      - docker_default
      - default
    labels:
      - "traefik.http.routers.sb.rule=Host(`sqp.localhost`) && PathPrefix(`/api`)"
    environment:
      - STRIPE_SECRET_KEY=hoge # stripe用secret key
      - ALLOWED_HOSTS=sqp.localhost
      - HTTPS=True
    depends_on:
      - db
  sqpf:
    build:
      context: front
      target: build
    expose:
      - "8080"
    command: yarn serve
    volumes:
      - ./front:/usr/src/app
    networks:
      - docker_default
      - default
    labels:
      - "traefik.http.routers.sf.rule=Host(`sqp.localhost`)"
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=sergtsop
      - POSTGRES_DB=sqp
    labels:
      - "traefik.enable=false"
  smh:
    image: mailhog/mailhog
    networks:
      - docker_default
      - default
    labels:
      - "traefik.http.services.smh.loadbalancer.server.port=8025"

networks:
  docker_default:
    external: true
    name: docker_default