services:
  sqpb:
    build:
      dockerfile_inline: |
        FROM python:3.10-slim as base
        WORKDIR /usr/src/app
        COPY back/requirements.txt .
        RUN apt update && apt -y install gcc make libpq-dev && pip install -r requirements.txt
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - ./back:/usr/src/app
    depends_on:
      - db
    networks:
      - docker_default
      - default
    labels:
      - "traefik.http.routers.sb.rule=Host(`sqp.localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.sb.tls=true"
    environment:
      - STRIPE_SECRET_KEY=hoge # stripe用secret key
      - DEBUG=True
      - ALLOWED_HOSTS=*
  sqpf:
    build:
      context: front
      target: base
    command: dev
    volumes:
      - ./front:/usr/src/app
    networks:
      - docker_default
      - default
    labels:
      - "traefik.http.routers.sf.rule=Host(`sqp.localhost`)"
      - "traefik.http.routers.sf.tls=true"
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=sergtsop
      - POSTGRES_DB=sqp
    labels:
      - "traefik.enable=false"
  smh:
    image: mailhog/mailhog
    networks:
      - docker_default
      - default
    labels:
      - "traefik.http.services.smh.loadbalancer.server.port=8025"

networks:
  docker_default:
    external: true
    name: docker_default