version: '3.8'
services:
  sqp-back:
    build: back
    volumes:
      - ./back:/usr/src/app
    networks:
      - docker_default
      - default
    labels:
      - "traefik.http.routers.sb.rule=Host(`sqp.sub.daco.dev`) && PathPrefix(`/api`)"
    environment:
      - STRIPE_SECRET_KEY=hoge # stripe用secret key
      - ALLOWED_HOSTS=sqp.sub.daco.dev
      - HTTPS=True
  sqp-front:
    build:
      context: front
      target: build
    expose:
      - "8080"
    command: yarn serve
    volumes:
      - ./front:/usr/src/app
    networks:
      - docker_default
      - default
    labels:
      - "traefik.http.routers.sf.rule=Host(`sqp.sub.daco.dev`)"
  sqp-db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=sqp
    labels:
      - "traefik.enable=false"
  smh:
    image: mailhog/mailhog
    networks:
      - docker_default
      - default
    labels:
      - "traefik.http.services.smh.loadbalancer.server.port=8025"

networks:
  docker_default:
    external: true
    name: docker_default