version: '3.8'
services:
  sqp-back:
    build: back
    volumes:
      - ./back:/usr/src/app
    networks:
      - docker_default
      - default
    labels:
      - "traefik.http.routers.sb.rule=Host(`${ALLOWED_HOSTS}`) && PathPrefix(`/api`)"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
  sqp-front:
    build: front
    volumes:
      - ./front:/usr/src/app
    networks:
      - docker_default
      - default
    labels:
      - "traefik.http.routers.sf.rule=Host(`${ALLOWED_HOSTS}`)"
  sqp-db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=sqp
    labels:
      - "traefik.enable=false"

networks:
  docker_default:
    external: true
    name: docker_default