version: '3.8'
services:
  sqp-back:
    build: back
    volumes:
      - ./back:/usr/src/app
    networks:
      - docker_default
      - default
    labels:
      - "traefik.http.routers.sb.rule=Host(`sqp.localhost`) && PathPrefix(`/api`)"
  sqp-front:
    build: front
    volumes:
      - ./front:/usr/src/app
    networks:
      - docker_default
      - default
    labels:
      - "traefik.http.routers.sf.rule=Host(`sqp.localhost`)"
  sqp-db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=sqp
    labels:
      - "traefik.enable=false"
  smh:
    image: mailhog/mailhog
    labels:
      - "traefik.http.services.smh.loadbalancer.server.port=8025"

networks:
  docker_default:
    external: true
    name: docker_default